### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by IneegoMontoya** [WestonV/RJI-Image-Classifier#5]
We ideally want to be able to have this application service multiple users, and be able to grade their  photos. But do not think we will have enough time to implement this feature

**Comment by sgoggins** [comment]
I think that's ok.

**Comment by antoniomv3** [comment]
We ended up feeling this functionality was not vital to our system so decided not to pursue it at this time. We have decided to leave the issue open as this could be a possibility in the future if development were to continue.
